# Generated by Django 5.1.6 on 2025-03-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tryrecipient',
            name='status',
            field=models.CharField(choices=[('Успешно', 'Успешно'),
                                            ('Не успешно', 'Не успешно')],
                                   default='Не успешно',
                                   verbose_name='Статус'),
        ),
    ]
