# Generated by Django 5.1.6 on 2025-03-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_tryrecipient_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='endDt',
            field=models.DateTimeField(verbose_name='Дата и время окончания отправки'),
        ),
    ]
