# Generated by Django 5.1.6 on 2025-03-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_mailing_enddt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='endDt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания отправки'),
        ),
    ]
